language: node_js
node_js:
after_success:
  - npm run coveralls
  - curl --data build=true -X POST https://registry.hub.docker.com/u/helderdiin/nodejs/trigger/1266e7a7-3a4b-42db-b04f-fd4870835896/
branches:
  only:
    - master